#!/usr/bin/env bash
# Installs HAProxy with the ff configurations:
# - Enables manage via the init script.
# - Distributes requests use a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 314812-web-01 34.232.67.194:80 check
    server 314812-web-02 54.165.182.162:80 check
EOT

sudo service haproxy restart
